import { registerEmit } from "../emits/emits.registry";

function registerMethodEmit(target: any, propertyKey: string | symbol, descriptor?: PropertyDescriptor) {
	const targetFn = descriptor?.value || target?.[propertyKey];

	if (typeof targetFn !== "function") {
		return descriptor;
	}

	return targetFn;
}

/**
 * Decorator for describing events generated by a microservice.
 * Generic type is required for generating payload schema. Should match the data structured passed into event payload.
 *
 * @param event - Event name without app prefix. Example: events/account/created. Prefix will be attached automatically.
 * @param resources - Resources in the payload. Required for policy checks and policy builder. Pass all models used in the payload.
 * @constructor
 */
export function Emits<T = unknown>(event: string, resources?: Function[]): MethodDecorator {
	return function (target: any, propertyKey: string | symbol, descriptor: PropertyDescriptor) {
		const targetFn = registerMethodEmit(target, propertyKey, descriptor);

		if (typeof targetFn === "function") {
			registerEmit(targetFn, {
				event,
				resources: resources,
				targetName: String(propertyKey),
				className: target?.constructor?.name,
			});
		}

		return descriptor;
	};
}
